---
title: "R Notebook"
output: html_notebook
---

```{r}
library(ggplot2)
library(dplyr)
library(lubridate)

theme_set(theme_bw())
```

##Transgender

```{r}
BreitbartTransgenderNGram <- read.csv("transgenderBigramPMI.csv")
```

```{r}
summary(BreitbartTransgenderNGram)
```

```{r}
craze <- list("transgender craze", "transgender ideology", "transgender activists", "transgender movement", "transgender lobby", "transgender advocates", "transgender trend")

athletics <- list("transgender cyclist", "transgender weightlifter", "transgender athletes", "transgender swimmer","transgender lifestyle", "transgender footballer")

militaryIndustrial <- list("transgender troop", 'transgender troops','transgender inmate','transgender prisoners', 'transgender inmates','transgender servicepeople', 'transgender soldier','transgender prisoner', 'transgender soldiers')
```

```{r}
BreitbartTransgenderNGram$n.gram <- as.factor(BreitbartTransgenderNGram$n.gram)

BreitbartTransgenderNGram <- BreitbartTransgenderNGram %>%
  mutate(theme = case_when(
    n.gram %in% craze ~ "ideology",
    n.gram %in% athletics ~ "athletics",
    n.gram %in% militaryIndustrial ~ "military industrial prison complex",
    TRUE ~ "other"
  ))
```



```{r}
BreitbartTransgenderNGram %>%
  filter(PMI >= 5) %>%
  ggplot(aes(x = reorder(n.gram,PMI), y=PMI, fill=theme, label=PMI)) +
  geom_bar(stat = "identity") +
  geom_text(aes(x=reorder(n.gram,PMI), y=PMI, hjust = -.2, label=trunc(PMI*10^2)/10^2)) + 
  coord_flip() +
  labs(x="Collocation", y="PMI", title="\"Transgender\" Collocations PMI in Breitbart Articles",fill="Theme") +
  scale_fill_brewer(palette = "Accent") + 
  ylim(0,7.5)
```

```{r}
ggsave("figures/BreitbartTransCollocationPMI.png")
```

### Pink News


```{r}
PinkNewsTransgenderNGram <- read.csv("PNtransgenderBigramPMI.csv")
```

```{r}
summary(PinkNewsTransgenderNGram)
```


```{r}
PinkNewsTransgenderNGram$n.gram <- as.factor(PinkNewsTransgenderNGram$n.gram)

PinkNewsTransgenderNGram <- PinkNewsTransgenderNGram %>%
  mutate(theme = case_when(
    n.gram %in% craze ~ "ideology",
    n.gram %in% athletics ~ "athletics",
    n.gram %in% militaryIndustrial ~ "military industrail prison complex",
    TRUE ~ "other"
  ))
```



```{r}
PinkNewsTransgenderNGram %>%
  filter(PMI >= 5) %>%
  ggplot(aes(x = reorder(n.gram,PMI), y=PMI, fill=theme, label=PMI)) +
  geom_bar(stat = "identity") +
  geom_text(aes(x=reorder(n.gram,PMI), y=PMI, hjust = -.2, label=trunc(PMI*10^2)/10^2)) + 
  coord_flip() +
  labs(x="Collocation", y="PMI", title="\"Transgender\" Collocations PMI in Pink News Articles",fill="Theme") +
  scale_fill_brewer(palette = "Accent") + 
  ylim(0,7.5)
```

## Biological 

### Breitbart

```{r}
BreitbartBiologicalNGram <- read.csv("biologicalBigramPMI.csv")
BreitbartBiologicalNGram$n.gram <- as.factor(BreitbartBiologicalNGram$n.gram)
```

```{r}
male <- list("biological males", "biological male", "biological men", "biological boys")

female <- list("biological females")

biology <- list("biological differences", "biological sex", "biological reality", "biological sexes")
```

```{r}
BreitbartBiologicalNGram$n.gram <- as.factor(BreitbartBiologicalNGram$n.gram)

BreitbartBiologicalNGram <- BreitbartBiologicalNGram %>%
  mutate(theme = case_when(
    n.gram %in% male ~ "AMAB",
    n.gram %in% female ~ "AFAB",
    n.gram %in% biology ~ "biology",
    TRUE ~ "other"
  ))
```

```{r}
BreitbartBiologicalNGram %>%
  filter(PMI >= 5) %>%
  ggplot(aes(x = reorder(n.gram,PMI), y=PMI, fill=theme, label=PMI)) +
  geom_bar(stat = "identity") +
  geom_text(aes(x=reorder(n.gram,PMI), y=PMI, hjust = -.2, label=trunc(PMI*10^2)/10^2)) + 
  coord_flip() +
  labs(x="Collocation", y="PMI", title="\"Biological\" Collocations PMI in Breitbart Articles",fill="Theme") +
  scale_fill_brewer(palette = "Paired") + 
  theme(text = element_text(size = 14)) + 
  ylim(0,9)
```

```{r}
ggsave("figures/BioCollocationPMI.png")
```

### Pink News

```{r}
PNBiologicalNGram <- read.csv("PNbiologicalBigramPMI.csv")
PNBiologicalNGram$n.gram <- as.factor(PNBiologicalNGram$n.gram)
```


```{r}
PNBiologicalNGram <- PNBiologicalNGram %>%
  mutate(theme = case_when(
    n.gram %in% male ~ "AMAB",
    n.gram %in% female ~ "AFAB",
    n.gram %in% biology ~ "biology",
    TRUE ~ "other"
  ))
```

```{r}
PNBiologicalNGram %>%
  filter(PMI >= 2) %>%
  ggplot(aes(x = reorder(n.gram,PMI), y=PMI, fill=theme, label=PMI)) +
  geom_bar(stat = "identity") +
  geom_text(aes(x=reorder(n.gram,PMI), y=PMI, hjust = -.2, label=trunc(PMI*10^2)/10^2)) + 
  coord_flip() +
  labs(x="Collocation", y="PMI", title="\"Biological\" Collocations PMI in Pink News Articles",fill="Theme") +
  scale_fill_brewer(palette = "Paired") + 
  theme(text = element_text(size = 14)) + 
  ylim(0,9)
```

##Biological

```{r}
BreitbartBiologicalNGram <- read.csv("BiologicalBigramRaw.csv")
```

```{r}
summary(BreitbartBiologicalNGram)
```

```{r}
BreitbartBiologicalNGram$n.gram <- as.factor(BreitbartBiologicalNGram$n.gram)
```


```{r}
BreitbartBiologicalNGram %>% 
  filter(PMI >= 50) %>% 
  ggplot(aes(x=reorder(n.gram,PMI), y=PMI)) + 
  geom_bar(stat = "identity") + 
  coord_flip() + 
  labs(x="Collocation", y="# of occurrences", title="\"Biological + [collocate]\" Counts in Breitbart Articles")
```

## Pink News

```{r}
PNBiologicalNGram <- read.csv("PNBiologicalBigramRaw.csv")
```

```{r}
summary(PNBiologicalNGram)
```

```{r}
PNBiologicalNGram$n.gram <- as.factor(PNBiologicalNGram$n.gram)
```


```{r}
PNBiologicalNGram %>% 
  filter(PMI >= 5) %>% 
  ggplot(aes(x=reorder(n.gram,PMI), y=PMI, label=PMI)) + 
  geom_bar(stat = "identity") + 
  geom_text() + 
  coord_flip() + 
  labs(x="Collocation", y="# of occurrences", title="\"Biological + [collocate]\" Counts in Breitbart Articles")
```

#Meta Data

##Breitbart

```{r}
Meta <- read.csv("textList.csv")
```


```{r}
Meta <- Meta %>% 
  unique()
```

```{r}
Meta$dateTime<-as.Date(Meta$dateTime)
```

```{r}
Meta %>% 
  group_by(month = lubridate::floor_date(dateTime, 'month')) %>% 
  summarise(count = n()) %>% 
  ggplot(aes(x=month, y=count)) + 
  geom_point(stat = "identity") + 
  geom_hline(yintercept = 19.35, color="pink")  + 
  geom_smooth() + 
  labs(x="Time",y="Number of Articles Posted", title = "Articles tagged \'transgender\' on Breitbart")
```

```{r}
Meta %>% 
  group_by(month = lubridate::floor_date(dateTime, 'month')) %>% 
  summarise(count = n()) %>% 
  summary()
```



###PN 

```{r}
PNMeta <- read.csv("PNtextList.csv") %>% 
  unique
```

```{r}
PNMeta <- PNMeta %>% 
  mutate(dateTime = lubridate::mdy(dateTime))

PNMeta$dateTime<-as.Date(PNMeta$dateTime)
```

```{r}
PNMeta %>% 
  group_by(month = lubridate::floor_date(dateTime, 'month')) %>% 
  summarise(count = n()) %>% 
  ggplot(aes(x=month, y=count)) + 
  geom_point(stat = "identity") + 
  geom_hline(yintercept = 11.75, color="pink")  + 
  geom_smooth() + 
  labs(x="Time",y="Number of Articles Posted", title = "Articles tagged \'transgender\' on Pink News")
```

```{r}
PNMeta %>% 
  group_by(month = lubridate::floor_date(dateTime, 'month')) %>% 
  summarise(count = n()) %>% 
  summary()
```





